apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: neeraj005/three-tier-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: Nodeport
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend